const Chinese = {
	language: "语言",
	China: "中国",

	tabbarhome: "主页",
	tabbarsearch: "搜索",
	tabbardeals: "折扣",
	tabbarjobs: "工作",
	tabbarme: "我",

	homesearchjobs: "搜索工作",
	homesearchgigs:"搜索",
	homediscountcard: "折扣卡",
	homedeals: "优惠",
	homeeditprofile: "编辑资料",
	homehelp: "签证 & 法律援助",
	homecontact: "联系我们",
	homepostjobs: "发布工作信息",
	homepostgigs:"发布",
	homeupgrade: "升级",
	homefeatured: "付费推广",
	homeadvertise: "广告营销",
	homepostevent: "发布活动",
	homecreatedeal: "创建交易",
	homeregister: "注册",

	homefeatjobs: "最近的工作:",
	homefeatdeals: "最新优惠折扣:",
	homefeateducator: "工作机会:",

	homebannergopro: "更新 & 升级专业版",
	homebannerfollowus: "关注最新资讯",
	homereviewtitle: "评价我们:",
	homereviewtxt: "期待您的建议希望提供更好的服务？...",
	homereviewbutton: "提交",
	homeapplyjob: "申请",

	roleIntrotop: "你好!",
	roleIntrobottom: "选择您的身份?",
	educatorbutton: "教育工作者",
	businessbutton: "教育相关企业",
	vendorbutton: "商户 (提供优惠折扣)",
	otherbutton: "访问者",

	mobile: "手机号码",
	verificationCode: "6位数验证码",
	getVerificationCode: "收取验证码",
	bindMobile: "让我们开始吧!",
	agree: "条款 & 条件",
	IncorrectPhoneNumber: "手机号已失效",
	pleasewait: "请稍等 & 再试一次",
	IncorrectVerificationCode: "哦！验证码错误...",
	incorrectagree: '同意条款 & 条件',

	basicinfowindowheader: "设置: 你的信息",
	Basicinfofirstname: "名字",
	basicinfolastname: "姓氏",
	basicinfonickname: "昵称 (选填)",
	basicinfoeducategory: "教育者分类 (可多选)",
	frstnameerror: "输入你的名字",
	lastnameerror: "输入你的姓氏",
	nationalityerror: "输入你的国籍",
	categoryerror: "至少选一种",
	jobtitleerror: "输入你的工作名称",
	workemailerror: "输入你的工作邮箱",
	basicinfobuton: "下一步",

	basicinfojobtitle: "职位名称",
	basicinfoworkemail: "工作邮箱",
	authenticationsuccessful: "身份验证成功",
	businessinfowindowheader: "设置: 企业信息",
	businessname: "企业 / 机构名称",
	businesscategory: "教育企业类型 (选1个)",
	businessnameerror: "输入企业名称",
	businesscategoryerror: "选一种",
	vendorinfowindowheader: "设置: 企业信息",
	vendorname: "企业名称",
	vendorcategory: "企业类型 (选1个)",
	vendornameerror: "输入企业名称",
	vendorcategoryerror: "选择一种",

	aboutyoupgtxt: "关于你的信息",
	gender: "性别",
	nationality: "国籍",
	birthdate: "出生日期",
	location: "地点",
	jobseeking: "找工作",
	publicprofile: "可公布的个人信息",
	aboutyoupgbutton: "第1步",

	profilephotopgtxt: "上传你最喜欢的头像吧!",
	uploaderror: "上传失败",
	profilephotopgbutton1: "第2步",
	profilephotopgbutton2: "稍后再试",
	uploadbuttontxt: "上传",

	lookinggreatpgtxt: "你的资料已经看起来很棒啦! 记得要完成50%的资料以后才能更好的使用其他功能哦.",
	lookinggreatpgbutton1: "添加更多个人信息",
	lookinggreatpgbutton2: "我的主页",


	welcomepagetxt: "耶 <名字>! 您现在正式成为基础版会员啦. 请至少完成50%的个人信息填写, 更好的使用更多的功能.",
	welcomepagetxtone: "欢迎来到 ESL Passport",
	welcomepagetxttwo: " 请至少完成50%的个人信息填写, 才能浏览和申请这些工作机会！",
	welcomepgbutton1: "完善我的个人信息",
	welcomepgbutton2: "稍后尝试",

	accountpgaccountinfo: "账户信息",
	accountpgeditprofile: "编辑个人信息",
	accountpgdiscount: "折扣卡",
	accountpglanguage: "语言",
	accountpgabout: "关于账户",
	accountpgcontact: "联系我们",
	accountpgmyjobs: "我的工作",
	accountpgmydeals: "我的交易",
	accountpgmyevents: "我的活动",

	accountinfo: "增加账户",
	accountinfoadd: "切换账户",
	accountchangelanguage: "切换语言",

	// account info 20201109
	accountinfovendorname: "商户名称",
	accountinfolevelofmembership: "会员等级",
	accountinfoemail: "邮箱",
	accountinfophone: "手机号码",
	accountinfonickname: "昵称",
	accountinfobusinessname: "企业名称",
	accountinfoback: "返回",

	// me 三种身份 20201109
	meeducator: "教育工作者",
	mebusiness: "教育相关企业",
	mevendor: "商户",
	meguest: "访客",

	editprofpercent: "<%>完成度",
	editprofdetail: "细节",
	editprofmedia: "媒体",
	editprofpref: "倾向选择",
	editprofdetailbasic: "基本信息",
	editprofdetailexperience: "经验",
	editprofdetailcred: "资格证书",
	editprofdetailinterest: "兴趣爱好",
	editprofdetailbio: "用几句话来让你的个人信息更显眼!",
	editprofdetailwork: "工作经验",
	editprofdetailworktitle: "工作名称",
	editprofdetailworkname: "公司",
	editprofdetailworklocation: "城市, 国家",
	editprofdetailworkstart: "开始日期",
	editprofdetailworkend: "结束日期",
	editprofdetailworktxt: "工作职责",
	editprofdetailedu: "工作经验",
	editprofdetaileduname: "学校/大学名称",
	editprofdetailedudegree: "学历",
	editprofdetailedufield: "专业",
	editprofdetailworkcountry: "国家",
	editprofdetailedugrad: "毕业年份",
	editprofdetailcert: "学历证书",
	editprofmediaprofile: "个人照片",
	editprofmediaheader: "横幅图片",
	editprofmediagallery: "相册 (6张)",
	editprofmediavideo: "视频",

	confirm: "确定",
	logout: "退出",
	languageSwitchSuc: "语言切换成功",
	Verified: "已验证",
	fillYourName: "请填入你的名字",
	fillEducatorName: "请填入教育工作者名字",
	fillBusinessName: "请填入企业名称",
	fillVendorName: "请填入商户名称",
	basic: "基础版",
	// deals
	dealsevents: "活动",
	dealsfintness: "健身类",
	dealshealth: "健康类",
	dealsfoodandbev: "食物 & 酒水",
	dealsspaandbeauty: "水疗 & 美容",
	dealsother: "其他",
	dealsshanghai: "上海",
	// deals 20201109
	dealsadddeal1: "加入第1个交易",
	dealsadddeal2: "加入第2个交易 (专业版)",
	dealsadddeal3: "加入第3个交易 (优享版)",
	dealsadddeal4: "加入第4个交易 (优享版)",
	dealsadddeal5: "加入第5个交易 (优享版)",
	dealsmoredeals: "升级账户添加更多的交易!",
	dealsedit: "编辑",
	dealsDetail: "详情",
	dealsdealordiscount: "这是一个优惠还是折扣",
	dealsdeal: "优惠",
	dealsdiscount: "折扣",
	dealsdealordisinfo: "优惠/折扣名字",
	dealsdisinfo: "折扣详情",
	dealsdealordisinfoph: "举例: 所有披萨半价哦..",
	dealsalllocationorlimited: "多个地点还是只有1个?",
	dealsalllocations: "所有的门店",
	dealslimited: "1个门店",
	dealspopularcity: "门店分类",
	dealsLocation: "城市 (在上海的哪个区)",
	dealslocationph: "请输入优惠区域",
	dealspartlocations: "参与的门店",
	dealschoosefile: "选择文件",
	dealscontractdur: "活动有效期至",
	dealsoneyears: "1年",
	dealstwoyears: "2年",
	dealsagreement: '交易协议',
	dealsunderstandtxt: "我明白这个交易提交需要先得到ESL Passport的批准.",

	// events 20201109
	eventsaddevent1: "加入活动1",
	eventsaddevent2: "加入活动2 (专业版)",
	eventsaddevent3: "加入活动3 (优享版)",
	eventsaddevent4: "加入活动4 (优享版)",
	eventsaddevent5: "加入活动5 (优享版)",
	eventsmoreevent: "升级账户添加更多的活动吧!",
	eventsedit: "编辑",
	eventsdetail: "详情",
	eventseventtype: "活动类型",
	eventssocial: "社交类",
	eventsprofessional: "商务类",
	eventseventname: "活动名称",
	eventseventnameph: "请输入活动名称",
	eventsdealordfem: "优惠/折扣 为ESL Passport的会员提供",
	eventsdealordfemph: "请输入优惠/折扣",
	eventseventdate: "活动日期",
	eventschoosedate: "选择日期",
	eventseventtime: "活动时间 (时-分)",
	eventsstartime: "开始时间",
	eventsendtime: "结束时间",
	eventsdescription: "活动介绍",
	eventsdescriptionph: "请添加活动介绍",
	eventspopularcity: "地点分类",
	eventslocation: "活动地点",
	eventslocationph: "请输入活动地点",
	eventseventflyer: "活动宣传页",
	eventschoosefile: "选择文件",
	eventscheckout: "活动页退出",
	eventscheckoutph: "请进入活动页退出",
	eventsagreement: "活动条款",
	eventsagreementtxt: "请确定已阅读并理解",
	eventssubmit: "确定",
	eventsviewfiles: "浏览文件",
	eventsstarttimeorendtimeph: "请选择正确的开始和结束时间",

	// profile  home
	profiledetail: "详情",
	profilemedia: "媒体",
	profilepreferences: "倾向选择",
	profilebasicinfo: "基本信息",
	profilefirstname: "名字",
	profilefirstnameph: "请输入你的名字",
	profilelastname: "姓氏",
	profilelastnameph: "请输入你的姓氏",
	profilefirstandlastname: "名字 & 姓氏",
	profilenickname: "昵称",
	profilenicknameph: "",
	profilecurrentcity: "当前城市",
	profilebirthdate: "出生日期",
	profilenationality: "国籍",
	profilegender: "性别",
	profilechoosegender: "选择性别",
	profilechoosenationality: "选择国籍",
	profilejobseeking: "搜索工作",
	profilepublicprofile: "公开的资料",
	profilecredentials: "资格证书",
	profilelanguages: "语言",
	profileeducation: "教育经历",
	profileschool: "学校",
	profileschoolph: "请输入你的学校名称",
	profiledegree: "学历",
	profiledegreeph: "请输入你的学历",
	profilefieldofstudy: "专业",
	profilefieldofstudyph: "请输入你的专业",
	profilework: "工作",
	profilegrade: "成绩",
	profilegradeph: "输入你的成绩",
	profileeducationtimes: "教育经历",
	profilechoosestartyear: "开始年份",
	profilechooseendyear: "结束年份",
	profilecertifications: "资历证书",
	profileexperience: "经验",
	profileworkexperience: "工作经验",
	profilejobtitle: "职位",
	profilejobtitleph: "请输入你的工作名称",
	profilecompanyname: "公司名称",
	profilecompanynameph: "输入你的公司名称",
	profileworklocation: "工作地点",
	profileworklocationph: "输入你的工作地点",
	profilelocation: "地点",
	profileworktime: "工作时间",
	profileteachingtimes: "教学经历",
	profileteachingexperience: "教学经验",
	profilechooseteachingexperience: "选择教学经历",
	profileworkdate: "工作日期",
	profilechooseworkdate: "选择开始日期",
	profilechooseenddate: "选择日期",
	profileresponsibilities: "职责",
	profileresponsibilitiesph: "你的工作职责",
	profilecountriestraveled: "旅游过的地区",
	profilecountrieslived: "生活过的地区",
	profileinterest: "兴趣爱好",
	profilebio: "个人经历",
	profilehobbies: "兴趣爱好",
	profileprofilephoto: "资料照片",
	profileheaderphoto: "横幅图片",
	profilepics6max: "资料照片 (最多6张)",
	profileintrovideo: "简介视频",
	profilesubject: "倾向的教学科目",
	profilejobtype: "倾向的工作类型",
	profileagetoteach: "倾向的学生教学年龄",
	profileregion: "倾向的区域",
	profilebenefits: "倾向的福利",
	profileedit: "编辑",
	profileyourcontactbasicinfo: "你的基本信息介绍",
	profilesmallbio: "简短介绍",
	profilesmallbioph: "我已经在教育行业工作5年了而且...",
	profilebusinessbasicinfo: "企业基本信息",
	profilebusinessbio: "企业信息介绍",
	profilebusinessbioph: "ABC学校是在1986年成立的，到目前为止在2个国家开设...",
	profileyearfounded: "成立年份",
	profilechooseyearfounded: "选择年份",
	profilebusinesslocation: "企业地点",
	profilewebsite: "网站",
	profilewebsiteph: "举例www.esl-passport.cn",
	profilebusinessphone: "公司手机号",
	profilebusinessphoneph: "请输入你的工作手机号",
	profilecontactname: "联系人",
	profilecontactnameph: "请输入你的联系人姓名",
	profilecontactphone: "联系手机号",
	profilecontactphoneph: "请输入你的联系人手机号",
	profilephone: "手机号码",
	profilecurriculum: "目录",
	profilecurriculumph: "请输入目录信息",
	profileaverageclasssize: "平均班级人数",
	profileaverageclasssizeph: "请输入班级平均人数",
	profiletechnologyavailable: "可用的技术平台",
	profiletechnologyavailableph: "请输入可用的技术平台",
	profilespecialneeds: "特殊需求",
	profileevents: "活动",
	profilefieldstrips: "外勤",
	profilecurrentlyhiring: "招聘中",
	profilestudentage: "学生年龄",
	profileourjobs: "我们的工作",
	profilebusinesslogo: "企业标识",
	profilecompanylegalinfo: "企业注册信息",
	profilecompanynameen: "公司名称",
	profilecompanynameenph: "(英文)",
	profilelegalcompanyname: "公司合法注册名称",
	profilelegalcompanynameph: "(中文)",
	profilebusinessregistrationnumber: "企业注册编号",
	profilebusinessregistrationnumberph: "18位",
	profilebusinesslicense: "工商许可证书",
	profileviewfiles: "浏览文件",
	profilecompanygeneralinfo: "公司大概信息",
	profilevendorbio: "商户介绍",
	profilevendorbioph: "告诉浏览者关于您公司更多的信息吧.",
	profilewechatofficialaccountid: "微信公众号ID",
	profilewechatofficialaccountidph: "",
	profilevendorwebsite: "网站",
	profilevendorwebsiteph: "www.businessname.com",
	profilevendorphone: "电话号码",
	profilevendorphoneph: "请输入您的手机号",
	profilevendorlocation: "地点",
	profiledogfriendly: "宠物狗友好",
	profilevendorevents: "您有活动需要发布吗?",
	profilevendorlogo: "标识",
	profileqrcode: "二维码",
	profilewechatofficialaccount: "(微信公众号)",
	profilefirstcontact: "倾向的联系方式",
	profilefirstlanguage: "倾向的沟通语言",
	// profile edit
	profileeditbasicinfo: "编辑基本信息",
	profileeditsubmit: "提交",

	// jobs 20201110
	jobsbusinessinfo: "企业信息",
	jobsjoblocation: "工作地点",
	jobsjoblocationph: "请输入工作地点",
	jobsbenefits: "福利",
	jobsgeneralpositioninfo: "职位信息简介",
	jobsjobtitle: "工作名称",
	jobsapplicationduedate: "申请截止日期",
	jobschooseduedate: "选择截止日期",
	jobsstartdate: "开始日期",
	jobsagetoteach: "教学学生年龄段",
	jobssubject: "科目",
	jobsemploymenttype: "工作类型",
	jobsonlinejob: "在线职位?",
	jobssalary: "薪资",
	jobssalaryph: "请输入薪水范围",
	jobspaymentperiod: "薪资支付方式",
	jobschoosepaymentperiod: "选择薪资支付方式",
	jobscurrency: "货币",
	jobspositiondesc: "职位简介",
	jobspositiondescph: "请输入职位简介",
	jobsnumberofvacancies: "空缺职位数量",
	jobsequalopportunity: "你会接受不同肤色的申请者吗？（平等机会)",
	jobsapplicantrequirements: "申请条件",
	jobsgender: "性别",
	jobschoosegender: "请选择性别",
	jobsteachingcertificate: "教学证书",
	jobscprcertified: "CPR证书",
	jobsfirstasidecertified: "急救证书",
	jobsteachingexperience: "教学经历",
	jobschooseteachingexperience: "请选择教学经历",
	jobsteachinglicense: "教学许可",
	jobseducation: "教育经历",
	jobschooseeducation: "选择教育经历",
	jobsnationality: "国籍",
	jobslanguages: "语言",
	jobsage: "年龄",
	jobssecret: "保密",
	jobscontactpersoninfo: "联系人信息",
	jobswillyouinterview: "您将会是面试官吗?",
	jobsname: "名字",
	jobsnameph: "请输入你的名字",
	jobsphoto: "照片",
	jobspriceforfreemembers: "免费基础版会员价格",
	jobsattentiontxt1: "请注意:在2020年结束前我们为您提供免费发布工作的机会！如果您想要发布的招聘职位有更多的浏览量，成为付费会员将会更容易让全世界的教育工作者注意到哦!",
	jobsattentiontxt2: "升级您的账户来在2021年获取更多的曝光量，无限制的招聘信息发布，以及长期的优惠吧 !",
	jobspostjob: "发布这个工作机会",

	jobscontactus: "联系我们",
	jobsapply: "申请",
	jobspositiondetails: "职位详情",
	jobsnativespeaker: "母语者",

	jobLocationErrorMsg: "请选择职位地点",
	jobTitleErrorMsg: '请选择职位名称',
	appDueDateErrorMsg: "请选择截止日期",
	startDateErrorMsg: "请选择开始日期",
	ageToTeachErrorMsg: "请选择学生的教学年龄",
	subjectErrorMsg: "请选择教学科目",
	employmentTypeErrorMsg: "请选择工作类型",
	salaryErrorMsg: "请输入薪资范围",
	paymentPeriodErrorMsg: "请输入薪资支付周期",
	currencyErrorMsg: "请选择货币",
	positionDescErrorMsg: "请选择职位介绍",
	teachingExpErrorMsg: "请选择教学经验",
	nativeSpeakerErrorMsg: "",
	jobschooseupto5: "最多选择5个",
	jobschooseupto4: "最多选择4个",
	// 20201020

	profilelanguagechoice: "选择语言类型",
	profilebusinesstoggleschool: "您代表的是学校吗？",
	profilebusinesstogglehiring: "您目前需要招聘吗?",

	// 20201119 新增
	accountinfobasicmember: "基础版会员",
	accountinfopromember: "专业版会员",
	accountinfoupgrade: "升级",
	// 20201119 me
	mebasiclevel: "会员等级：基础版",
	meprolevel: "会员等级：专业版",
	mepluslevel: "会员等级：优享版",
	meupgrade: "升级",
	// 20201120
	legalbusinesslicense: "请上传营业执照",
	// 20201121
	dealsdealcheckout: "",

	// 20201123
	jobsmyapplyjobslistemptyph: "好像您还没有申请任何职位哦！",
	jobsminsalaryph: "输入最少薪资",
	jobsmaxsalaryph: "输入最高薪资",
	dealscheckedagreement: "请查看协议",
	dealsdogfriendly: "对狗友好",

	eventseventprice: "活动票价",
	eventseventpriceph: "请输入活动票价",
	// 20201124
	basicbusinesstwochooselocation: "选择地点",
	// 20201125
	jobsmyjobsapproved: "确认",
	jobsmyjobsunderreview: "审核中",
	jobsmyjobsrejected: "拒绝",

	basiceduapplicationcontact: "申请者联系方式",
	basiceduapplicationcontactph: "请输入微信号，邮箱，或电话号码 #",
	basiceduemail: "邮箱",
	basiceduemailph: "输入你的邮箱",

	profileapplicationcontact: "申请者联系方式",
	profilechoosepreferredlanguageph: "选择语言类型",

	// 20201126
	memyapplications: "我的申请",
	profilebusinesseducationinfo: "教育背景",

	jobsdetailcompensation: "报酬",
	jobsdetailonline: "线上",
	jobslistemploymentfulltime: "全职",
	jobslistemploymentparttime: "兼职",
	jobslistemploymentseasonal: "季度性",

	profilebusinesssubjectsweteach: "教学课程",
	profilebusinessemploymentbenefits: "福利",
	profilebusinessourstudentage: "学生年龄段 ",
	profilebusinesscompanypolicies: "公司政策",
	profilebusinesscurrentopenpositions: "现有开放职位",

	eventsaddchooseeventdate: "选择活动日期",

	accountinfoname: "姓名",

	dealsrecentdeals: "最近的优惠折扣",
	// 20201130
	locationselectprovince: "选择省份",
	locationselectcity: "选择城市",
	locationselectdistrict: "选择区域",

	// 20201201
	welcomebusinesspagetxtone: "欢迎来到ESL Passport",
	welcomebusinesspagetxttwo: "发布职位招聘和接收申请需要完成至少50%的信息填写",
	welcomevendorpagetxtone: "欢迎来到ESL Passport",
	welcomevendorpagetxttwo: "提交优惠或折扣信息以及发布活动信息需要完成至少50%的信息填写.",

	dealsaddonelocation: "一个地点",
	dealsaddmorethanonelocation: "多余一个地点",
	dealsadddeal: "优惠折扣",
	dealsadddiscount: "折扣",
	dealsaddaddress: "地址",
	dealsaddaddressph: "请收入优惠地址",
	dealsaddoneyear: "1 年",
	dealsaddtwoyear: "2 年",

	profilebusinessbasicisschool: "您是学校吗？",
	profilebusinessbasicturnontoggels: "点击以下选项如果你是...",

	accountinfoneedhelp: "需要帮助吗?",
	jobsaddcompensation: "综合的",
	jobspostequalopportunity: "平等机会",
	jobsposthione: "你好！我是",
	educatorwechatid: "微信号",
	businesswechatid: "微信号",
	vendorwechatid: "微信号",
	//20201203
	jobsunderreviewnote: "提示语:",
	jobsunderreviewnotetxt: "耶！我们很高兴看到您发布新工作职位！请稍等审核通过哦！最多24小时。",
	dealsnote: "提示语:",
	dealsnotetxt: "耶！我们很高兴看到您发布新的优惠信息，您的客户经理已收到，将很快的为您审核哦！",
	eventsnote: "提示语:",
	eventsnotetxt: "耶！我们很高兴看到您发布新的活动信息，请稍等我们团队审核哦！",

	//20201204
	dealsaddlocationcategoryph: "Please select the location category",
	vendorwechatidph: "Please enter your WeChat Id",

	//20201208
	dealsmyapproved: "Approved",
	dealsmyunderreview: "Under Review",
	dealsmyrejected: "Rejected",

	//20201209
	profilebusinessinfobusinessname: "Business Name",
	profilebusinessinfobusinessnameph: "Please enter business name",

	//20201216
	dealsadddealdescription: "Deal/Discount Description",
	dealsadddealdescriptionph: "Deal Details ",
	profilevendorbasicaddress: "Address",
	profilevendorbasicaddressph: "Please enter address",

	//20201217
	profilesharecompanyinfo: "Company Info",
	profileeducategory: "Educator Category",
	photomediahelpsone: "Media Helps",
	photomediahelpstwo: "You STAND OUT!",
	photomediahelpsthree: "Upload is automatic",

	//20201221
	jobslistjobtype: "Job Type",
	jobslistjobtypeunlimited: "All",
	jobslistjobtypefulltime: "Full-time",
	jobslistjobtypeparttime: "Part-time",
	jobslistjobtypeseasonal: "Seasonal",
	jobsliststudentage: "Student(s) Age",
	jobsliststudentageunlimited: "All",

	jobslistgender: "Gender",
	jobslistgenderunlimited: "All",
	jobslistgenderone: "Male",
	jobslistgendertwo: "Female",
	jobslistgenderthree: "None",
	jobslistfilterreset: "Reset",
	jobslistfilterconfirm: "Confirm",

	//20201224
	firstloginprompt: "Make sure you follow the official WeChat account to use this App",
	eduwechatid: "WeChat Id",
	eduwechatidph: "Please enter your WeChat Id",
	applicationcontactinfo: "Contact Info",

	//20201229
	edushareprofilepics: "Profile pics",
	shareprofilename: "Name",

	eduprofilecompanyname: "Company",
	eventplace: "Place/Shop",
	eventplaceph: "Enter the Place/Shop",
	eventdetailaddress: "Detail address",
	eventdetailaddressph: "Enter the Detail address",
	eventticketprice: "Ticket Price",
	eventeventtime: "Event Time",

	//20200111
	myjobsopenclose: "Close/Open",
	myjobsviews: "View",
	myjobspromotion: "Promotion",

	//20210305
	applyjobmodaltips: "提示",
	applyjobmodalcontent: "您确定要申请这个职位吗？",
	applyjobmodalconfirmtext: "确定",
	applyjobmodalcanceltext: "取消",

	authorizeforlogin: "授权获取用户信息",

	profilebusinessschoolinfo: "School Information",
	vendorapplication: "Vendor Application",
	vendorapplicationaboutyou: "About You",
	vendorapplicationname: "Name",
	vendorapplicationphone: "Phone #",
	vendorapplicationbusinfo: "Business Info",

	vendorphonenumber: "Manager's phone number",
	vendorcompanynameen: "English",
	vendorcompanynamecn: "Chinese",
	vendorcompanywebsite: "Company Website",
	vendorproposeddeal: "Proposed Deal",
	vendorproposeddealph: "10% off all set meals",
	vendorlookinggreatpgtxt1: "Your profile is starting to look great!",
	vendorlookinggreatpgtxt2: "Our Account Manager Will be in touch soon",
	vendorlocation: "Location",

	loginauthtxt: "One more step",

}

const English = {
	language: "Language",
	China: "China",

	tabbarhome: "Home",
	tabbarsearch: "Search",
	tabbardeals: "Deals",
	tabbarjobs: "Jobs",
	tabbarme: "Me",

	homesearchjobs: "Search Jobs",
	homesearchgigs:"Search Gigs",
	homediscountcard: "Discount Card",
	homedeals: "Deals",
	homeeditprofile: "Edit Profile",
	homehelp: "Visa & Legal Help",
	homecontact: "Contact Us",
	homepostjobs: "Post Jobs",
	homepostgigs:"Post Gigs",
	homeupgrade: "Go Pro",
	homefeatured: "Get Featured",
	homeadvertise: "Advertisment",
	homepostevent: "Post Event",
	homecreatedeal: "Offer A Deal",
	homeregister: "Sign Up",

	homefeatjobs: "Recent Jobs:",
	homefeatdeals: "New Deals:",
	homefeateducator: "Job Seeking Educators:",

	homebannergopro: "Upgrade & Go Pro",
	homebannerfollowus: "Stay In The Loop",
	homereviewtitle: "Review Us:",
	homereviewtxt: "Tell us how we are doing...",
	homereviewbutton: "Submit",
	homeapplyjob: "Apply",

	roleIntrotop: "Hello!",
	roleIntrobottom: "Which one are you?",
	educatorbutton: "Educator",
	businessbutton: "Education Business",
	vendorbutton: "Vendor (Deal Program)",
	otherbutton: "Guest",

	mobile: "Phone #",
	verificationCode: "6 Digit Code",
	getVerificationCode: "get code",
	bindMobile: "Let's Go!",
	agree: "Terms & Conditions",
	IncorrectPhoneNumber: "Invaild Phone #",
	pleasewait: "Please Wait & Try Again",
	IncorrectVerificationCode: "Opps, wrong code...",
	incorrectagree: 'Agree to the Terms & Conditions',

	basicinfowindowheader: "Set Up: About You",
	Basicinfofirstname: "First Name",
	basicinfolastname: "Last Name",
	basicinfonickname: "Nickname",
	basicinfoeducategory: "Educator Category (Multi-Select)",
	frstnameerror: "Enter your first name",
	lastnameerror: "Enter your last name",
	nationalityerror: "Enter your nationality",
	categoryerror: "Choose at least one category",
	jobtitleerror: "Enter your job title",
	workemailerror: "Enter your work email",
	basicinfobuton: "Next",

	basicinfojobtitle: "Job Title",
	basicinfoworkemail: "Work Email",
	authenticationsuccessful: "Authentication is successful",
	businessinfowindowheader: "Set Up: Business Info",
	businessname: "Business / Institution Name",
	businesscategory: "Edu-Business Category (Choose 1)",
	businessnameerror: "Enter Business Name",
	businesscategoryerror: "Choose 1 Category",
	vendorinfowindowheader: "Set Up: Business Info",
	vendorname: "Business Name",
	vendorcategory: "Business Category (Choose 1)",
	vendornameerror: "Enter Business Name",
	vendorcategoryerror: "Choose 1 Category",

	aboutyoupgtxt: "About You",
	gender: "Gender",
	nationality: "Nationality",
	birthdate: "Birthdate",
	location: "Location",
	jobseeking: "Job Seeking",
	publicprofile: "Public Profile",
	aboutyoupgbutton: "Step 1 of 2",

	profilephotopgtxt: "Upload a favorite headshot!",
	uploaderror: "Upload Failed",
	profilephotopgbutton1: "Step 2 of 2",
	profilephotopgbutton2: "Maybe Later",
	uploadbuttontxt: "Upload",

	lookinggreatpgtxt: "Your profile is starting to look great! Remember you need 50% of it completed before using many features.",
	lookinggreatpgbutton1: "Add More To Profile",
	lookinggreatpgbutton2: "My Homepage",


	welcomepagetxt: "Yay <FIRST NAME>! You are now officially a Basic Member. Complete at least 50% of your profile, so that you can start using features.",
	welcomepagetxtone: "Welcome to ESL Passport",
	welcomepagetxttwo: " Complete at least 50% of your profile, so that you can start reviewing and applying to positions.",
	welcomepgbutton1: "Complete My Profile",
	welcomepgbutton2: "Maybe Later",

	accountpgaccountinfo: "Account Info",
	accountpgeditprofile: "Edit My Profile",
	accountpgdiscount: "Discount Card",
	accountpglanguage: "Change Language",
	accountpgabout: "About",
	accountpgcontact: "Contact ESL Passport",
	accountpgmyjobs: "My Jobs",
	accountpgmydeals: "My Deals",
	accountpgmyevents: "My Events",

	accountinfo: "Add Account",
	accountinfoadd: "Switch Account",
	accountchangelanguage: "Change Language",

	// account info 20201109
	accountinfovendorname: "Vendor Name",
	accountinfolevelofmembership: "Membership Level",
	accountinfoemail: "Email",
	accountinfophone: "Phone #",
	accountinfonickname: "Nickname",
	accountinfobusinessname: "Business Name",
	accountinfoback: "Back",

	// me 三种身份 20201109
	meeducator: "Educator",
	mebusiness: "Business",
	mevendor: "Vendor",
	meguest: "Guest",

	editprofpercent: "<%>Complete",
	editprofdetail: "Details",
	editprofmedia: "Media",
	editprofpref: "Preferences",
	editprofdetailbasic: "Basic Info",
	editprofdetailexperience: "Experience",
	editprofdetailcred: "Credentials",
	editprofdetailinterest: "Interest",
	editprofdetailbio: "Use a few sentences to help your profile standout!",
	editprofdetailwork: "Work Experience",
	editprofdetailworktitle: "Job Title",
	editprofdetailworkname: "Company",
	editprofdetailworklocation: "City, Country",
	editprofdetailworkstart: "Start Date",
	editprofdetailworkend: "End Date",
	editprofdetailworktxt: "Job Responsibilites",
	editprofdetailedu: "Work Experience",
	editprofdetaileduname: "School/University Name",
	editprofdetailedudegree: "Degree Level",
	editprofdetailedufield: "Field of Study",
	editprofdetailworkcountry: "Country",
	editprofdetailedugrad: "Graduation Year",
	editprofdetailcert: "Certificates",
	editprofmediaprofile: "Profile Photo",
	editprofmediaheader: "Header Photo",
	editprofmediagallery: "Gallery Photos (6)",
	editprofmediavideo: "Video",

	confirm: "Ok",
	logout: "Logout",
	languageSwitchSuc: "Language Switched Successfully",
	Verified: "Verified",
	fillYourName: "Fill in the name",
	fillEducatorName: "Fill in the educator name",
	fillBusinessName: "Fill in the business name",
	fillVendorName: "Fill in the vendor name",
	basic: "Basic",
	// deals
	dealsevents: "Events",
	dealsfintness: "Fitness",
	dealshealth: "Health",
	dealsfoodandbev: "Food & Bev",
	dealsspaandbeauty: "Spa & Beauty",
	dealsother: "Other",
	dealsshanghai: "Shanghai",
	// deals 20201109
	dealsadddeal1: "Add Deal 1",
	dealsadddeal2: "Add Deal 2 (Pro)",
	dealsadddeal3: "Add Deal 3 (Plus)",
	dealsadddeal4: "Add Deal 4 (Plus)",
	dealsadddeal5: "Add Deal 5 (Plus)",
	dealsmoredeals: "Upgrade to unlock more deals!",
	dealsedit: "Edit",
	dealsDetail: "Detail",
	dealsdealordiscount: "Is this a Deal or Discount",
	dealsdeal: "Deal",
	dealsdiscount: "Discount",
	dealsdealordisinfo: "Deal/Discount Name",
	dealsdisinfo: "Discount Info",
	dealsdealordisinfoph: "Example: 50% off all pizzas..",
	dealsalllocationorlimited: "Multiple Locations or 1?",
	dealsalllocations: "All Locations",
	dealslimited: "1 Location",
	dealspopularcity: "Location Category",
	dealsLocation: "City (District if Shanghai)",
	dealslocationph: "Please enter deal location",
	dealspartlocations: "Participating Locations",
	dealschoosefile: "Choose File",
	dealscontractdur: "Contract Duration",
	dealsoneyears: "1 year",
	dealstwoyears: "2 years",
	dealsagreement: 'Deal Agreement',
	dealsunderstandtxt: "I understand this deal will need ESL Passport's approval.",

	// events 20201109
	eventsaddevent1: "Add Event 1",
	eventsaddevent2: "Event 2 (Pro)",
	eventsaddevent3: "Event 3 (Plus)",
	eventsaddevent4: "Event 4 (Plus)",
	eventsaddevent5: "Event 5 (Plus)",
	eventsmoreevent: "Upgrade to unlock more events!",
	eventsedit: "Edit",
	eventsdetail: "Detail",
	eventseventtype: "Event Type",
	eventssocial: "Social",
	eventsprofessional: "Professional",
	eventseventname: "Event Name",
	eventseventnameph: "Enter the Event's Name",
	eventsdealordfem: "Deal/Discount For ESL Passport Members",
	eventsdealordfemph: "Enter the deal/discount you will offer our members.",
	eventseventdate: "Event Date",
	eventschoosedate: "Choose Date",
	eventseventtime: "Event Time",
	eventsstartime: "Start Time",
	eventsendtime: "End Time",
	eventsdescription: "Event Description",
	eventsdescriptionph: "Please enter event description",
	eventspopularcity: "Location Category",
	eventslocation: "Event Location",
	eventslocationph: "Enter the Event Location",
	eventseventflyer: "Event Flyer",
	eventschoosefile: "Choose File",
	eventscheckout: "Event Checkout",
	eventscheckoutph: "Enter event checkout",
	eventsagreement: "Event Agreement",
	eventsagreementtxt: "Please read and mark you understand",
	eventssubmit: "Submit",
	eventsviewfiles: "View Files",
	eventsstarttimeorendtimeph: "Select correct start time or end time",

	// profile  home
	profiledetail: "Detail",
	profilemedia: "Media",
	profilepreferences: "Preferences",
	profilebasicinfo: "Basic Info",
	profilefirstname: "First Name",
	profilefirstnameph: "",
	profilelastname: "Last Name",
	profilelastnameph: "",
	profilefirstandlastname: "First Name & Last Name",
	profilenickname: "Nickname",
	profilenicknameph: "",
	profilecurrentcity: "Current City",
	profilebirthdate: "Birthdate",
	profilenationality: "Nationality",
	profilegender: "Gender",
	profilechoosegender: "Choose Gender",
	profilechoosenationality: "Choose Nationality",
	profilejobseeking: "Job Seeking",
	profilepublicprofile: "Public Profile",
	profilecredentials: "Credentials",
	profilelanguages: "Languages",
	profileeducation: "Education",
	profileschool: "School",
	profileschoolph: "China University",
	profiledegree: "Degree",
	profiledegreeph: "Doctorate, Master's, Bachelor's, etc...",
	profilefieldofstudy: "Field of Study",
	profilefieldofstudyph: "Chemistry, International Business, Dance, etc.",
	profilework: "Work",
	profilegrade: "Grade",
	profilegradeph: "Enter your grade",
	profileeducationtimes: "Duration of Study",
	profilechoosestartyear: "Start Year",
	profilechooseendyear: "End Year",
	profilecertifications: "Certifications",
	profileexperience: "Experience",
	profileworkexperience: "Work Experience",
	profilejobtitle: "Job Title",
	profilejobtitleph: "Please enter your job title",
	profilecompanyname: "Company Name (Enlgish)",
	profilecompanynameph: "ABC Academy",
	profileworklocation: "Work Location",
	profileworklocationph: "Please enter your work location",
	profilelocation: "Location",
	profileworktime: "Duration",
	profileteachingtimes: "Teaching Times",
	profileteachingexperience: "Teaching Experience",
	profilechooseteachingexperience: "Choose",
	profileworkdate: "Work Duration",
	profilechooseworkdate: "Start Date",
	profilechooseenddate: "End Date",
	profileresponsibilities: "Responsibilities",
	profileresponsibilitiesph: "Your responsibilities",
	profilecountriestraveled: "Places Traveled:",
	profilecountrieslived: "Places Lived:",
	profileinterest: "Interest",
	profilebio: "Bio",
	profilehobbies: "Hobbies",
	profileprofilephoto: "Profile Photo",
	profileheaderphoto: "Header Photo",
	profilepics6max: "Profile pics (6 max)",
	profileintrovideo: "Intro Video",
	profilesubject: "Preferred Subject to Teach",
	profilejobtype: "Preferred Job Type",
	profileagetoteach: "Preferred Age To Teach",
	profileregion: "Preferred Region",
	profilebenefits: "Preferred Benefits",
	profileedit: "Edit",
	profileyourcontactbasicinfo: "Your Basic Info",
	profilesmallbio: "Short Bio",
	profilesmallbioph: "I have been working in education for 5 years and...",
	profilebusinessbasicinfo: "Business Information",
	profilebusinessbio: "Business Introduction",
	profilebusinessbioph: "ABC school opened in 1986 and is now in two countries...",
	profileyearfounded: "Year Founded",
	profilechooseyearfounded: "Choose Year",
	profilebusinesslocation: "Business Location",
	profilewebsite: "Website",
	profilewebsiteph: "www.eslpassport.com",
	profilebusinessphone: "Business Phone #",
	profilebusinessphoneph: "",
	profilecontactname: "Contact Name",
	profilecontactnameph: "",
	profilecontactphone: "Contact Phone #",
	profilecontactphoneph: "",
	profilephone: "Phone #",
	profilecurriculum: "Curriculum",
	profilecurriculumph: "Oxford Reading Tree, McGraw Hill, etc...",
	profileaverageclasssize: "Average class size",
	profileaverageclasssizeph: "25 Students",
	profiletechnologyavailable: "Technology Available",
	profiletechnologyavailableph: "Computers, Smart screens, 3D Printing, etc.",
	profilespecialneeds: "Special Needs",
	profileevents: "Events",
	profilefieldstrips: "Fields Trips",
	profilecurrentlyhiring: "Currently Hiring",
	profilestudentage: "Student Age",
	profileourjobs: "Company Policies:",
	profilebusinesslogo: "Business Logo",
	profilecompanylegalinfo: "Company Legal Info",
	profilecompanynameen: "Company Name",
	profilecompanynameenph: "(English)",
	profilelegalcompanyname: "Legal Company Name",
	profilelegalcompanynameph: "(Chinese)",
	profilebusinessregistrationnumber: "Business Registration ID",
	profilebusinessregistrationnumberph: "18 Characters",
	profilebusinesslicense: "Business License",
	profileviewfiles: "View Files",
	profilecompanygeneralinfo: "Company General Info",
	profilevendorbio: "Vendor Introduction",
	profilevendorbioph: "Tell veiwers about your business.",
	profilewechatofficialaccountid: "WeChat Official Account ID",
	profilewechatofficialaccountidph: "",
	profilevendorwebsite: "Website",
	profilevendorwebsiteph: "www.businessname.com",
	profilevendorphone: "Phone #",
	profilevendorphoneph: "Please enter your phone number",
	profilevendorlocation: "Location",
	profiledogfriendly: "Dog Friendly",
	profilevendorevents: "Do you have events?",
	profilevendorlogo: "Logo",
	profileqrcode: "QR Code",
	profilewechatofficialaccount: "(WeChat Official Account)",
	profilefirstcontact: "Preferred Method of Contact",
	profilefirstlanguage: "Preferred Language",
	// profile edit
	profileeditbasicinfo: "Edit Profile Basic",
	profileeditsubmit: "Submit",

	// jobs 20201110
	jobsbusinessinfo: "Job Details:",
	jobsjoblocation: "Job Location",
	jobsjoblocationph: "District, City",
	jobsbenefits: "Benefits",
	jobsgeneralpositioninfo: "General Position Info:",
	jobsjobtitle: "Job Title",
	jobsapplicationduedate: "Application Deadline",
	jobschooseduedate: "Choose Deadline",
	jobsstartdate: "Start Date",
	jobsagetoteach: "Student(s) Age",
	jobssubject: "Subject(s)",
	jobsemploymenttype: "Employment Type",
	jobsonlinejob: "Is this an Online Job?",
	jobssalary: "Salary",
	jobssalaryph: "Enter salary or salary range",
	jobspaymentperiod: "Payment Period",
	jobschoosepaymentperiod: "Choose Payment Period",
	jobscurrency: "Currency",
	jobspositiondesc: "Position Description",
	jobspositiondescph: "Please enter position description",
	jobsnumberofvacancies: "Number of Vacancies",
	jobsequalopportunity: "Will you accept applicant of different skin colors? (Equal Opportunity)",
	jobsapplicantrequirements: "Applicant Requirements",
	jobsgender: "Gender",
	jobschoosegender: "Choose Gender",
	jobsteachingcertificate: "Teaching Certificate(s)",
	jobscprcertified: "CPR Certified",
	jobsfirstasidecertified: "First Aid Certified",
	jobsteachingexperience: "Teaching Experience",
	jobschooseteachingexperience: "Choose Teaching Experience",
	jobsteachinglicense: "Teaching License",
	jobseducation: "Minimum Education Certificate",
	jobschooseeducation: "Choose Degree Level",
	jobsnationality: "Nationality",
	jobslanguages: "Languages",
	jobsage: "Age",
	jobssecret: "Secret",
	jobscontactpersoninfo: "Contact Person Info",
	jobswillyouinterview: "Will you be doing the interview?",
	jobsname: "Name",
	jobsnameph: "Please enter your name",
	jobsphoto: "Photo",
	jobspriceforfreemembers: "Basic (Free) Member: Prices",
	jobsattentiontxt1: "Job's are free to post in 2020! For more views, fill this form fully out.",
	jobsattentiontxt2: "Upgrade to get cheaper featuring & unlimited free job posting in 2021!",
	jobspostjob: "Post This Job!",

	jobscontactus: "Contact Us",
	jobsapply: "Apply",
	jobspositiondetails: "Position Details",
	jobsnativespeaker: "Native Speaker",

	jobLocationErrorMsg: "Select a Job Location",
	jobTitleErrorMsg: "Select a Job Title",
	appDueDateErrorMsg: "Select a Due Date",
	startDateErrorMsg: "Select a Start Date",
	ageToTeachErrorMsg: "Select the Students Age",
	subjectErrorMsg: "Select a Subject",
	employmentTypeErrorMsg: "Select the Employment Type",
	salaryErrorMsg: "Enter in the Salary",
	paymentPeriodErrorMsg: "Select the Payment Period",
	currencyErrorMsg: "Select the Payment Currency",
	positionDescErrorMsg: "Complete the Position Description",
	teachingExpErrorMsg: "Select the Preferred Teaching Experience",
	nativeSpeakerErrorMsg: "Select the Required Teacher",
	jobschooseupto5: "Choose up to 5",
	jobschooseupto4: "Choose up to 4",
	// 20201020

	profilelanguagechoice: "Type Language Here",
	profilebusinesstoggleschool: "Are you a school?",
	profilebusinesstogglehiring: "Are you currently hiring?",

	// 20201119 新增
	accountinfobasicmember: "Basic Member",
	accountinfopromember: "Pro Member",
	accountinfoplusmember: "Plus Member",
	accountinfoupgrade: "Upgrade",
	// 20201119 me
	mebasiclevel: "Membership: Basic",
	meprolevel: "Membership: Pro",
	mepluslevel: "Membership: Plus",
	meupgrade: "Upgrade",

	// 20201120
	legalbusinesslicense: "Please upload business license",
	// 20201121
	dealsdealcheckout: "",

	// 20201123
	jobsmyapplyjobslistemptyph: "Looks like you haven't applied to any jobs...",
	jobsminsalaryph: "Enter min salary",
	jobsmaxsalaryph: "Enter max salary",
	dealscheckedagreement: "Please checked agreement",
	dealsdogfriendly: "Dog Friendly",

	eventseventprice: "Event Ticket Price",
	eventseventpriceph: "Please enter event ticket price",
	// 20201124
	basicbusinesstwochooselocation: "Choose Location",
	// 20201125
	jobsmyjobsapproved: "Approved",
	jobsmyjobsunderreview: "Under Review",
	jobsmyjobsrejected: "Rejected",

	basiceduapplicationcontact: "Application Contact",
	basiceduapplicationcontactph: "Enter your application contact",
	basiceduemail: "Email",
	basiceduemailph: "Enter your email",

	profileapplicationcontact: "Application Contact",
	profilechoosepreferredlanguageph: "Choose Preferred Language",

	// 20201127 new add 
	memyapplications: "My Applications",
	profilebusinesseducationinfo: "Education Info",

	jobsdetailcompensation: "Compensation",
	jobsdetailonline: "Online",
	jobslistemploymentfulltime: "FT",
	jobslistemploymentparttime: "PT",
	jobslistemploymentseasonal: "S",

	profilebusinesssubjectsweteach: "Subjects We Teach",
	profilebusinessemploymentbenefits: "Employment Benefits",
	profilebusinessourstudentage: "Our Students Age",
	profilebusinesscompanypolicies: "Company Policies",
	profilebusinesscurrentopenpositions: "Current Open Positions",

	eventsaddchooseeventdate: "Choose event date",

	accountinfoname: "Name",

	dealsrecentdeals: "Recent Deals",
	// 20201130
	locationselectprovince: "Select Province",
	locationselectcity: "Select City",
	locationselectdistrict: "Select District",

	// 20201201
	welcomebusinesspagetxtone: "Welcome to ESL Passport",
	welcomebusinesspagetxttwo: "Complete at least 50% of your profile to start posting jobs & receiving applications.",
	welcomevendorpagetxtone: "Welcome to ESL Passport",
	welcomevendorpagetxttwo: "Complete at least 50% of your profile to start submitting your deal/discount offers & posting events.",

	dealsaddonelocation: "One location",
	dealsaddmorethanonelocation: "More than one location",
	dealsadddeal: "Deal",
	dealsadddiscount: "Discount",
	dealsaddaddress: "Address",
	dealsaddaddressph: "Please enter deal address",
	dealsaddoneyear: "1 year",
	dealsaddtwoyear: "2 year",

	//20201202
	profilebusinessbasicisschool: "Are you a School?",
	profilebusinessbasicturnontoggels: "Turn on these toggels if you are..",

	//new
	accountinfoneedhelp: "Need Help?",
	jobsaddcompensation: "Compensation:",
	jobspostequalopportunity: "Equal Opportunity",
	jobsposthione: "Hi, I'm",
	educatorwechatid: "WeChat ID",
	businesswechatid: "WeChat ID",
	vendorwechatid: "WeChat ID",

	//20201203
	jobsunderreviewnote: "Note:",
	jobsunderreviewnotetxt: "Yay, we love new jobs! Wait for your job to be approved (24 hrs max).",
	dealsnote: "Note:",
	dealsnotetxt: "Yay, we love new deals! Please note, an Account Manager will review all new deal submissions.",
	eventsnote: "Note:",
	eventsnotetxt: "Yay, we love new events! Wait for our team to review.",

	//20201204
	dealsaddlocationcategoryph: "Please select the location category",
	vendorwechatidph: "Please enter your WeChat Id",

	//20201208
	dealsmyapproved: "Approved",
	dealsmyunderreview: "Under Review",
	dealsmyrejected: "Rejected",

	//20201209
	profilebusinessinfobusinessname: "Business Name",
	profilebusinessinfobusinessnameph: "Please enter business name",

	//20201216
	dealsadddealdescription: "Deal/Discount Description",
	dealsadddealdescriptionph: "Deal Details ",
	profilevendorbasicaddress: "Address",
	profilevendorbasicaddressph: "Please enter address",

	//20201217
	profilesharecompanyinfo: "Company Info",
	profileeducategory: "Educator Category",
	photomediahelpsone: "Media Helps",
	photomediahelpstwo: "You STAND OUT!",
	photomediahelpsthree: "Upload is automatic",

	//20201221
	jobslistjobtype: "Job Type",
	jobslistjobtypeunlimited: "All",
	jobslistjobtypefulltime: "Full-time",
	jobslistjobtypeparttime: "Part-time",
	jobslistjobtypeseasonal: "Seasonal",
	jobsliststudentage: "Student(s) Age",
	jobsliststudentageunlimited: "All",

	jobslistgender: "Gender",
	jobslistgenderunlimited: "All",
	jobslistgenderone: "Male",
	jobslistgendertwo: "Female",
	jobslistgenderthree: "None",
	jobslistfilterreset: "Reset",
	jobslistfilterconfirm: "Confirm",

	//20201224
	firstloginprompt: "Make sure you follow the official WeChat account to use this App",
	eduwechatid: "WeChat Id",
	eduwechatidph: "Please enter your WeChat Id",
	applicationcontactinfo: "Contact Info",

	//20201229
	edushareprofilepics: "Profile pics",
	shareprofilename: "Name",

	eduprofilecompanyname: "Company",
	eventplace: "Place/Shop",
	eventplaceph: "Enter the Place/Shop",
	eventdetailaddress: "Detail address",
	eventdetailaddressph: "Enter the Detail address",
	eventticketprice: "Ticket Price",
	eventeventtime: "Event Time",

	//20200111
	myjobsopenclose: "Close/Open",
	myjobsviews: "View",
	myjobspromotion: "Promotion",

	//20210305
	applyjobmodaltips: "Tips",
	applyjobmodalcontent: "Are you sure you want to apply for this position?",
	applyjobmodalconfirmtext: 'Sure',
	applyjobmodalcanceltext: "Cancel",

	filterjobsalary1: "0-5000",
	filterjobsalary2: "5000-10000",
	filterjobsalary3: "10000-15000",
	filterjobsalary4: "15000 and above",

	authorizeforlogin: "Authorize",

	profilebusinessschoolinfo: "School Information",
	vendorapplication: "Vendor Application",
	vendorapplicationaboutyou: "About You",
	vendorapplicationname: "Name",
	vendorapplicationphone: "Phone #",
	vendorapplicationbusinfo: "Business Info",

	vendorphonenumber: "Manager's phone number",
	vendorcompanynameen: "English",
	vendorcompanynamecn: "Chinese",
	vendorcompanywebsite: "Company Website",
	vendorproposeddeal: "Proposed Deal",
	vendorproposeddealph: "10% off all set meals",
	vendorlookinggreatpgtxt1: "Your profile is starting to look great!",
	vendorlookinggreatpgtxt2: "Our Account Manager Will be in touch soon",
	vendorlocation: "Location",

	loginauthtxt: "One more step",



}

module.exports = {
	'Chinese': Chinese,
	'English': English
}
